# Generated by Django 3.1.5 on 2021-01-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.TextField(default=None, max_length=500, verbose_name='Описание'),
        ),
    ]
